name: Sync to Hugging Face hub
on:
  push:
    branches: [main, master, Task/Splitter-Local]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Sync with Hugging Face Space
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: jesusmanuel1020/Splitter-Local
          hf_token: ${{ secrets.SPLITTER_SECRETS }}
          repo_type: space
          space_sdk: gradio