name: Sync to Hugging Face hub
on:
  push:
    branches: [main, master, Task/Splitter-Local] # <-- Añade tu rama aquí

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Validate HF token
        run: |
          if [ -z "${{ secrets.SPLITTER_SECRETS }}" ]; then
            echo "Error: SPLITTER_SECRETS is not set in repository secrets"; exit 1
          fi

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.SPLITTER_SECRETS }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://jesusmanuel1020:${HF_TOKEN}@huggingface.co/spaces/jesus-camacho/moises-local
          git push --force origin HEAD:main
